### ISSUE TITLE
Crash when answering the first question

### ISSUE THREAD

**Issue by NormalGaussian** [NormalGaussian/vocab-builder#13]
Removed pickle files, ran latest version of the game at commit a5e82e3f43248c95b369f6dc440f869db5607d2b

<details>
<summary>Expand for log</summary>

```bash
Your score is 0 and you require 10 points to continue with your life.

"In an incongruous manner."


Which of the following words pertain to this definition?

   1.) wen
   2.) incongruously
   3.) assiduously
   4.) agog

Please enter an integer from 1 - 4
>>> 2

Correct!

Traceback (most recent call last):
  File "/home/eoin/Coding/vocab-builder/./game_engine.py", line 67, in <module>
    start()
  File "/home/eoin/Coding/vocab-builder/./game_engine.py", line 36, in start
    if generate_and_ask_question() == True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eoin/Coding/vocab-builder/gen_game_choices.py", line 220, in generate_and_ask_question
    update_correct(answer, answer_type) # Updates the concurrent correct guesses for this definition
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eoin/Coding/vocab-builder/gen_game_choices.py", line 97, in update_correct
    working_bytype_dict[word_type][word]["concurrent_correct"] +=1
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'incongruously'
```

</details>

**Comment by NormalGaussian** [comment]
This can also occur when I answer the question incorrectly

<details>
<summary>Expand for log</summary>

```bash
Your score is 0 and you require 10 points to continue with your life.

"A riot aimed at persecution or massacre of a particular ethnic or religious group, usually Jews."


Which of the following words pertain to this definition?

   1.) eidolon
   2.) pogroms
   3.) imbroglio
   4.) palimpsest

Please enter an integer from 1 - 4
>>> 1

You have failed! Bow your head in shame.

Traceback (most recent call last):
  File "/home/eoin/Coding/vocab-builder/./game_engine.py", line 67, in <module>
    start()
  File "/home/eoin/Coding/vocab-builder/./game_engine.py", line 36, in start
    if generate_and_ask_question() == True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eoin/Coding/vocab-builder/gen_game_choices.py", line 226, in generate_and_ask_question
    update_wrong(answer, answer_type)
  File "/home/eoin/Coding/vocab-builder/gen_game_choices.py", line 137, in update_wrong
    working_bytype_dict[word_type][word]["concurrent_wrong"] +=1
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'pogroms'
eoin@Marasi:~/Coding/vocab-builder$ 
```

</details>

**Comment by NormalGaussian** [comment]
nb. this doesn't always occur. I got onto the second question. I didn't get further.

**Comment by thezeit** [comment]
Resolved
