### ISSUE TITLE
Entered seemingly infinite loop

### ISSUE THREAD

**Issue by NormalGaussian** [NormalGaussian/vocab-builder#14]
Played game, answered first question correctly and the game entered what seemed to be an infinite loop. One core at 100% for >1 minute.

<details>
<summary>Expand for log</summary>

```bash
Your score is 0 and you require 10 points to continue with your life.

"Casually unconcerned; carefree, indifferent, nonchalant."


Which of the following words pertain to this definition?

   1.) maudlin
   2.) piqued
   3.) insouciant
   4.) etiolated

Please enter an integer from 1 - 4
>>> 3

Correct!

^CTraceback (most recent call last):
  File "/home/eoin/Coding/vocab-builder/./game_engine.py", line 67, in <module>
    start()
  File "/home/eoin/Coding/vocab-builder/./game_engine.py", line 36, in start
    if generate_and_ask_question() == True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eoin/Coding/vocab-builder/gen_game_choices.py", line 220, in generate_and_ask_question
    update_correct(answer, answer_type) # Updates the concurrent correct guesses for this definition
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eoin/Coding/vocab-builder/gen_game_choices.py", line 100, in update_correct
    while True:
          ^^^^
KeyboardInterrupt
```

I exited using Ctrl+C

**Comment by thezeit** [comment]
Nesting error - resolved
